pretrained: false
check_freq: 2000
save_freq: 2000
gradient_save_freq: 1000
save_path: "./models/a2c"
log_dir: "./logs/a2c"
total_timesteps: 5000000
log_interval: 1000
policy: "CnnPolicy"
learning_rate: 7.0e-4
gamma: 0.99
n_steps: 5
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
use_rms_prop: true
rms_prop_eps: 1.0e-5
normalize_advantage: false
stats_window_size: 100
policy_kwargs: null
verbose: 2
seed: 42

n_stack: 4
n_envs: 4
env_id: "BreakoutNoFrameskip-v4"

saved_model_path: "./models/a2c/A2C_Breakout.zip"
unzip_file_path: "./models/a2c/A2C_Breakout_unzipped"
log_to_wandb: true
project_train: "Atari_Algo_Comparision_train"
project_test: "Atari_Algo_Comparision_test"
entity: "yashashwi-singhania-bce23-iit-bhu"
name_train: "A2C_breakout_train"
name_test: "A2C_breakout_test"
notes: "A2C Breakout"
sync_tensorboard: true
test_episodes: 100 