pretrained: false
check_freq: 2000
save_freq: 2000
gradient_save_freq: 1000
save_path: "./models/dqn"
log_dir: "./logs/dqn"
total_timesteps: 5000000
log_interval: 1000
policy: "CnnPolicy"
learning_rate: 1.0e-4
gamma: 0.99
buffer_size: 100000
learning_starts: 10000
batch_size: 64
tau: 1.0
train_freq: 4
gradient_steps: 1
target_update_interval: 1000
exploration_fraction: 0.1
exploration_initial_eps: 1.0
exploration_final_eps: 0.05
max_grad_norm: 10
stats_window_size: 100
policy_kwargs: null
verbose: 2
seed: 42

n_stack: 4
n_envs: 1
env_id: "BreakoutNoFrameskip-v4"

saved_model_path: "./models/DQN/DQN_Breakout.zip"
unzip_file_path: "./models/DQN/DQN_Breakout_unzipped"
log_to_wandb: true
project_train: "Atari_Algo_Comparision_train"
project_test: "Atari_Algo_Comparision_test"
entity: "yashashwi-singhania-bce23-iit-bhu"
name_train: "DQN_breakout_train"
name_test: "DQN_breakout_test"
notes: "DQN Breakout"
sync_tensorboard: true
test_episodes: 100 