pretrained: false
check_freq: 2000
save_freq: 2000
gradient_save_freq: 1000
save_path: "./models/ppo"
log_dir: "./logs/ppo"
total_timesteps: 2000000
log_interval: 1000
policy: "CnnPolicy"
learning_rate: 5.0e-4
gamma: 0.99
n_steps: 64
batch_size: 256
n_epochs: 8
gae_lambda: 0.95
clip_range: 0.2
clip_range_vf: 1
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: false
sde_sample_freq: -1
target_kl: 0.5
normalize_advantage: false
stats_window_size: 100
policy_kwargs: null
verbose: 2
seed: 42

n_stack: 4
n_envs: 4
env_id: "BreakoutNoFrameskip-v4"

saved_model_path: "./models/PPO/PPO_Breakout.zip"
unzip_file_path: "./models/PPO/PPO_Breakout_unzipped"
log_to_wandb: true
project_train: "Atari_Algo_Comparision_train"
project_test: "Atari_Algo_Comparision_test"
entity: "yashashwi-singhania-bce23-iit-bhu"
name_train: "PPO_breakout_train"
name_test: "PPO_breakout_test"
notes: "PPO Breakout"
sync_tensorboard: true
test_episodes: 100 
